language: php

before_install:
  - sudo apt-get update
  - sudo apt-get install -y silversearcher-ag

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_script:
    - composer self-update
    - composer install

script:
    - vendor/bin/php-cs-fixer fix --config=.php_cs --quiet --dry-run
    - bin/PHPJumpToDefinition --file tests/data/function/call_function.php --line 8 --column 1 --keyword "this_is_a_check_function"
    - vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
    - php buildPHAR.php

after_success:
    - bash <(curl -s https://codecov.io/bash)
